version: '3.5'
services:
  api:
    build: ./
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "postgresql://todo-user:todo-password@database/todo"
      HOST: "0.0.0.0"
      PORT: 8000
      FLASK_DEBUG: 1
    depends_on:
      - database
      - db-upgrade-migration

  db-upgrade-migration:
    build: ./
    container_name: db-upgrade-migration
    volumes:
      - ./:/usr/src/app/
    environment:
      DATABASE_URL: "postgresql://todo-user:todo-password@database/todo"
      FLASK_APP: /usr/src/app/run-db-migrations.py
    command: sh -c "flask db upgrade"
    depends_on:
      - db-generate-migration

  db-generate-migration:
    build: ./
    container_name: db-generate-migration
    volumes:
      - ./:/usr/src/app/
    environment:
      DATABASE_URL: "postgresql://todo-user:todo-password@database/todo"
      FLASK_APP: /usr/src/app/run-db-migrations.py
    command: sh -c "flask db migrate -m "generating a new migration""
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15.2-alpine
    container_name: database
    environment:
      POSTGRES_PASSWORD: todo-password
      POSTGRES_USER: todo-user
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U \"todo-user\" -d todo'"
        ]
      interval: 5s
      timeout: 5s
      retries: 2
